huskyroboticsteam/Resurgence

src/CMakeLists.txt
src/Constants.h
src/Globals.cpp
src/Globals.h
src/Networking/CANStubs.cpp
src/Networking/CANUtils.cpp
src/Networking/CANUtils.h
src/Networking/FakeBaseStation.cpp
src/Networking/FakeCANBoard.cpp
src/Networking/Network.cpp
src/Networking/Network.h
src/Networking/NetworkingStubs.cpp
src/Networking/NetworkingStubs.h
src/Networking/ParseBaseStation.cpp
src/Networking/ParseBaseStation.h
src/Networking/ParseCAN.cpp
src/Networking/ParseCAN.h
src/Networking/log.cpp
src/Networking/log.h
src/Networking/tests.cpp

Since we're working on networking, we should probably just use the branch called "networking". We can keep using the same development pattern though (just pushing directly to networking, rather than constantly making new branches and pull requests).

Merge nathan3 into networking

---

.gitmodules
src/Autonomous.cpp
src/Autonomous.h
src/CMakeLists.txt
src/Networking/Network.cpp
src/Networking/Network.h
src/Rover.cpp
tests-docker-action/entrypoint.sh

To test:
```
make RoverSim
./RoverSim
```
You should see the simulator window pop open, and the robot should be driving in a slow circle.

Create RoverSim executable that runs Rover.cpp in the simulator

---

src/Autonomous.cpp

Also update the simulator to be smaller-scale (for development purposes). New version:

Add comments describing breakdown of autonomy integration

---

src/CMakeLists.txt
src/filters/PoseEstimator.cpp
src/filters/PoseEstimator.h
src/kinematics/DiffDriveKinematics.cpp
src/kinematics/DiffDriveKinematics.h

In preparation of writing tests for the kinematics code, I refactored the pose estimator to put the differential drive kinematics math into a separate class (`DiffDriveKinematics`), which will make it cleaner and easier to test.
I modified the `PoseEstimator` class to use the new `DiffDriveKinematics` class as well.

Differential Drive Kinematics

---

src/filters/ExtendedKalmanFilter.h
src/filters/KalmanFilterBase.h

There are no code changes in this PR, it just clarifies some expectations and requirements of the NoiseCovMat and KalmanFilterBase classes.

Improved documentation of some parts of EKF and KF

---

src/CMakeLists.txt
tests/filters/EKFTest.cpp
tests/filters/RollingAvgFilterTest.cpp
tests/filters/StateSpaceUtilsTest.cpp
tests/kinematics/DiffDriveKinematicsTest.cpp

Added unit tests, mostly concerning the new filter code.

Added unit tests

---

src/Autonomous.cpp

Unfortunately, in testing, this still doesn't avoid collisions all of
the time (or even most of the time), but at least it tries a bit harder.

Each timestep, check whether the plan collides, and replan if necessary

---

src/CMakeLists.txt
src/worldmap/GlobalMap.cpp
src/worldmap/GlobalMap.h
src/worldmap/TrICP.cpp
src/worldmap/TrICP.h
tests/worldmap/GlobalMapTest.cpp
tests/worldmap/TrICPTest.cpp

This adds a global lidar map, which I've tested and it works okayish with the robot sim. This PR doesn't hook it up to the autonomous code since I still need to add in a few performance enhancements, as well some accuracy improvements. I wanted to merge it in before continuing because otherwise the PR might get too big.
It adds the code for global mapping, as well as some unit tests that verify behavior.
After merging, I'll continue work on improving it.

Added working global lidar map - will improve

---

enable_CAN.sh
src/CMakeLists.txt
src/Networking/FakeCANBoard.cpp
src/Networking/ParseCAN.cpp
src/Networking/TestPackets.cpp

Creates a script to set up the CAN interfaces on the Jetson, updates the FakeCANBoard script to send some motor control packets.

Update CAN version / other changes from CAN 

---

src/Autonomous.cpp
src/Autonomous.h
src/PlanViz.cpp

This commit also demonstrates how we can use the PoseArray message type
to send a long list of points all at once. It also starts to think about
how we'll eventually use transform frames.
When we move to 3D, we're going to have to come up with a better way to
associate landmark location information with the ID of the landmark.
Right now we use that the z-value is zero, which might not work well
once we have landmarks where the z-value is important.

Visualize landmarks in PlanViz

---

src/Autonomous.h
src/CMakeLists.txt
src/planning/navigation.cpp
src/planning/plan.cpp
src/planning/plan.h
src/planning/search.cpp
src/planning/search.h

Added removed files from the submodule, updated references, updated CMakeLists, etc.
`navigation.cpp`, `search.cpp`, and `search.h` aren't directly used by our code anywhere, but they're referenced in the CMakeLists and they're added to executables. Does that mean we still want them around, or should I delete them?

Added planning files, updated submodule reference

---

enable_CAN_and_GPS.sh
src/CMakeLists.txt
src/Networking/CANUtils.cpp
src/Networking/real_world_interface.cpp
src/Rover.cpp
src/Util.cpp
src/Util.h
src/gps/read_usb_gps.cpp
src/gps/read_usb_gps.h

I tested this on the hardware; see comment below.

Implement real-world readGPS

---

src/CMakeLists.txt
src/Constants.h
src/Networking/FakeCANBoard.cpp
src/Networking/Network.cpp
src/Rover.cpp

From testing on the robot yesterday / today.

Fix aruco linking error and other small fixes

---

src/Autonomous.cpp
src/CMakeLists.txt
src/Networking/Network.cpp
src/Networking/ParseBaseStation.cpp
src/Networking/motor_interface.cpp
src/Networking/real_world_interface.cpp
src/Networking/tests.cpp
src/Rover.cpp
src/Util.cpp
src/Util.h
src/commands/CommandBase.h
src/commands/nogps/DriveThroughGate.cpp
src/commands/nogps/DriveThroughGate.h
src/commands/nogps/DriveToGate.cpp
src/commands/nogps/DriveToGate.h
src/gps/read_usb_gps.cpp

I'm sorry that this PR is such a mess. Please check individual commits for more information.
It's true that no-heading-sensor navigation doesn't quite work yet, but this is a good start.
This commit also implements readOdom by integrating the command velocities.

Merge no-gps stuff and other fixes from on-rover testing

---

.motion/camera2.conf
.motion/motion.conf
camera-config/cameras.rules
src/Autonomous.cpp
src/CMakeLists.txt
src/Networking/ParseBaseStation.cpp
src/Networking/motor_interface.cpp
src/Networking/tests.cpp
src/ar/CMakeLists.txt

Friday changes on the rover

---

src/Autonomous.cpp
src/Autonomous.h
src/CMakeLists.txt
src/PlanViz.cpp
src/Rover.cpp

Our EKF assumes that we have a heading sensor, which in general we might not have. This PR implements a slightly more general solution for localization (and mapping) that uses a pose graph. The pose graph code is in the `simulator` subrepo, so this PR just updates our main autonomy code to use that API.

Use pose graphs for localization

---

src/CMakeLists.txt
src/Networking/FakeCANBoard.cpp

I tested these on the rover and was able to move the three main motors (drill elevation, drill rotation, and soil drawer open/close).

Add science station packets to FakeCANBoard

---

src/Networking/websocket/WebSocketProtocol.cpp
src/Networking/websocket/WebSocketProtocol.h
src/Networking/websocket/WebSocketServer.cpp
src/Networking/websocket/WebSocketServer.h

This PR introduces a feature that is required for the simulator interface, as well as a bug fix and some minor improvements.
1. Fixed a bug where the client field associated with a protocol wasn't reset when a client disconnects.
2. Minor improvements to logging format.
3. Minor improvements to documentation.
4. Added connection and disconnection event handlers for protocols, which are necessary in some cases.

Bug fixes and improvements to WS server

---

src/world_interface/noop_world.cpp
src/world_interface/real_world_interface.cpp
src/world_interface/simulator_world.cpp
src/world_interface/world_interface.h

This is in preparation for interfacing with the IMU. I'm adding it now since I'll be implementing this method in the simulator interfacing branch.

added readHeading() method

---

src/CMakeLists.txt
src/base64/base64.cpp
src/base64/base64.h
src/base64/base64_img.cpp
src/base64/base64_img.h

This adds base64 code under the `base64` namespace. It also adds code for encoding/decoding opencv Mats to/from base64.

Added base64 encoding/decoding utilities

---

src/ar/MarkerSet.cpp
src/ar/MarkerSet.h

- Updated AR Tag for the 2022 season
- Removed unnecessary ALVAR functions and variables

Update ar tag

---

src/world_interface/kinematic_common_interface.cpp
src/world_interface/real_world_constants.h

Small PR that tunes all but one of the arm PWM scales, and fixes a bug with the differential. Now, the arm works with teleop as expected, except for the arm base which is untested due to not having a motor right now.

Tuned arm scales, fixed differential bug

---

camera-config/ForearmCameraCalibration.yml
camera-config/HandCameraCalibration.yml
src/Constants.h
src/network/MissionControlProtocol.cpp
src/world_interface/real_world_constants.h
src/world_interface/real_world_interface.cpp

With this pr the robot should be fully teleoperable I think

Created camera configs, tuned more arm

---

README.md
easy-install.sh
easy_install.sh

The script can be used to install all dependencies at once.
Also, adds instructions on IDE setup.

More improvements to setup instructions, create easy install script

---

src/Globals.cpp
src/Globals.h
src/Rover.cpp
src/TunePID.cpp
src/log.cpp
src/log.h

Made log level specifiable using command line argument.

Log level console arg

---

.github/workflows/ccpp.yml

Should fix pushes from outside collaborators.

Trigger CI on PR

---

src/Rover.cpp

Fixes for loop that looped infinitely and did not use its iteration variable.
Also, run clang-format over the file.

Change for loop to while loop + clang-format

---

src/CAN/CAN.cpp
src/CAN/CAN.h
src/CAN/CANMotor.cpp
src/CAN/CANMotor_AVR.cpp
src/CAN/CANMotor_PSOC.cpp

Many devices use pull packets so this will be very useful for all of them.

Add ability to schedule periodic telemetry pull packets

---

LICENSE

License changed from Apache 2.0 to GNU GPL v3

---

.github/workflows/format-checker.yml

This adds a CI pipeline to check if newly added code adheres to our style guide.

Add format checker

---

.clang-format
.github/workflows/ccpp.yml
src/CMakeLists.txt
src/TunePID.cpp
src/network/MissionControlProtocol.cpp
src/world_interface/data.cpp
src/world_interface/data.h
src/world_interface/kinematic_common_interface.cpp
src/world_interface/real_world_constants.h
src/world_interface/simulator_interface.cpp

We no longer have a differential so this removes those values and updates usages.

Update motor mappings for new wrist

---

.github/workflows/format-checker.yml

Some options we configure are introduced in clang-format-11, so update the dependency.

Use clang-format 11

---

src/world_interface/real_world_constants.h

Update drive PWM scales

---

src/network/MissionControlProtocol.cpp
src/world_interface/simulator_interface.cpp

Fix crashes for unsupported motors, and fixed units of joint position report.

Fix misc sim bugs

---

src/Rover.cpp
src/world_interface/data.cpp
src/world_interface/data.h

Fixed version of previous attempt of building this branch

added servo to peripheral_t enum

---

rover-config/README.md
rover-config/rover-config.sh

Easier to run rover-config.sh then copy each and every file manually.

rover-config: Add script to automate file copying + update readme

---

.github/workflows/ccpp.yml
easy_install.sh
src/CAN/CANMotor.cpp
src/CAN/CANMotor.h
src/CMakeLists.txt

finished pca servo method

---

.github/workflows/ccpp.yml
easy_install.sh
update_deps.sh

Factor out duplicated code in CI script and install script. Also added a convenient script to update all dependencies.

Centralize dependency list in script

---

src/CMakeLists.txt
src/LimitCalib.cpp
src/world_interface/noop_world.cpp
src/world_interface/real_world_constants.h
src/world_interface/real_world_interface.cpp
src/world_interface/simulator_interface.cpp
src/world_interface/world_interface.h

Added a Limit Switch Calibration executable and modified world interface initialization function along with CMake

Initial Limit Switch zero calibration test.

---

src/world_interface/real_world_interface.cpp

Minor refactoring to reduce code duplication

Improve camera init

---

README.md
src/CMakeLists.txt
src/gps/dummy/dummy_gps.cpp

Clean up cmake for gps in preparation for ardupilot stuff

Cleanup gps cmake

---

README.md
src/CMakeLists.txt
src/Constants.h
src/Globals.cpp
src/Globals.h
src/gps/dummy/dummy_gps.cpp
src/world_interface/real_world_constants.h

Arm ik creation

---

src/control/PlanarArmController.h

We'll be calling this bad boy from multiple threads so let's make it thread safe

Make arm controller threadsafe

---

src/CMakeLists.txt
src/Constants.h
src/ardupilot/ArduPilotInterface.cpp
src/ardupilot/ArduPilotInterface.h
src/ardupilot/ArduPilotProtocol.cpp
src/ardupilot/ArduPilotProtocol.h
src/navtypes.h
src/network/MissionControlProtocol.cpp
src/world_interface/real_world_interface.cpp

* Add orientation_t to navtypes
* Handle pixhawk messages for GPS, IMU, and heading

ArduPilotProtocol: Create protocol for ardupilot messages

---

src/world_interface/real_world_interface.cpp

We don't have a lidar or use CV tag detection, so no point in having that code running.

Remove unused features from world interface

---

src/Constants.h

Set ik speed

---

src/network/MissionControlProtocol.cpp
src/world_interface/data.cpp
src/world_interface/data.h
src/world_interface/kinematic_common_interface.cpp
src/world_interface/world_interface.h

This PR cleans up some joint-related code.
* It removes the drill arm joint, since we don't do anything with it
* It factors out some common code for getting the position of multiple joints at once

Cleanup for joint code

---

rover-config/50-rover-cameras.rules
rover-config/rover-config.sh
src/world_interface/real_world_interface.cpp

Update camera udev rules to properly identify and mount the hand and mast cameras.

Update camera configs

---

src/Rover.cpp
src/world_interface/simulator_interface.cpp

Fix deadlock where world interface waits for sim but sim initializes before server.
Also add active suspension.

Fix sim connection

---

rover-config/50-rover-cameras.rules

It no work before, it work now

Update cam config

---

.github/workflows/format-checker.yml

We installed the alternative but then didn't set it. This fixes that

Make CI work

---

src/world_interface/real_world_constants.h

Negate wheels

---

update_deps.sh

As tested on the Jetson Orin NX

Ensure Correct libopencv-dev Version

---

src/world_interface/kinematic_common_interface.cpp
src/world_interface/world_interface.h

Removed:
- readodom
- getcmdvel
- setcmdveltointegrate
- lastodom
- commandedWheelVel
- readodom

Removed unneeded odometry code

---

src/Rover.cpp
src/navtypes.h
src/world_interface/noop_world.cpp
src/world_interface/real_world_interface.cpp
src/world_interface/simulator_interface.cpp
src/world_interface/world_interface.h

We don't use or even implement these methods

Remove deprecated and vestigial methods from world interface

---

src/CMakeLists.txt
src/network/MissionControlProtocol.cpp
src/network/MissionControlTasks.cpp
src/world_interface/data.h
src/world_interface/gps_common_interface.cpp
src/world_interface/kinematic_common_interface.cpp
src/world_interface/motor/base_motor.cpp
tests/util/DataTest.cpp

- Remove the implicit cast, which is probably a very easy way to introduce bugs
- Fix all usages to check if a datapoint is valid before accessing it
- Change behavior of accessing invalid datapoint from UB to throwing a specific exception

Improve DataPoint safety

---

src/CMakeLists.txt

Make rover_common STATIC

---

src/network/CMakeLists.txt

Fix broken build

---

src/TunePID.cpp
src/world_interface/real_world_constants.h

Update tunepid and tuned constants

---

src/world_interface/real_world_constants.h

Tune last swerve

---

src/Rover.cpp
src/network/websocket/WebSocketServer.cpp

Fixed bugs related to setting custom log levels, added a new verbose log level, and adjusted some of the more verbose logs.

Fix some logging bugs and improve log levels

---

src/gps/dummy/dummy_gps.cpp

Not 100% sure if this is what you were talking about

add readIMUHeading method in dummy_gps

---

camera-config/BoxCamera.yml
camera-config/DrillCamera.yml
camera-config/HandCameraCalibration.yml
camera-config/MastCameraCalibration.yml
camera-config/Microscope.yml
camera-config/RandCameraCalibration.yml
camera-config/WristCameraCalibration.yml
camera-config/global.yml
rover-config/50-rover-cameras.rules
src/CAN/CAN.cpp
src/CMakeLists.txt
src/Constants.cpp
src/Constants.h
src/camera/Camera.cpp
src/camera/Camera.h
src/camera/CameraConfig.h
src/network/MissionControlProtocol.cpp
src/network/MissionControlTasks.cpp
src/network/MissionControlTasks.h
src/world_interface/data.cpp
src/world_interface/data.h
src/world_interface/real_world_interface.cpp
src/world_interface/simulator_interface.cpp
src/world_interface/world_interface.h

Aims to simplify our camera library, allows for easier configuration of camera streams

Rework Cameras to use GStreamer Pipelines

---

src/CAN/CMakeLists.txt
src/CMakeLists.txt
src/Constants.cpp
src/camera/CMakeLists.txt
src/control_interface.cpp
src/navtypes.h
src/world_interface/simulator_interface.cpp

Added unimplemented world interface methods
Edited CMake to only build libraries relevant to the specified world interface

Fix Simulator Interface + Optimize CMake
