huskyroboticsteam/Resurgence

src/CMakeLists.txt
src/Network.cpp
src/Rover.cpp

A few small changes to make the current code compile:
- not include linux headers on non-linux targets
- not rely on the symbols that those headers define
- make the target language C++11 so the compiler doesn't complain about enum classes

make 2020 compile (on Mac OS)

---

src/CMakeLists.txt
src/Globals.cpp
src/Globals.h
src/Network.cpp
src/Network.h
src/Networking/CANUtils.cpp
src/Networking/CANUtils.h
src/Networking/FakeBaseStation.cpp
src/Networking/FakeCANBoard.cpp
src/Networking/Network.cpp
src/Networking/Network.h
src/Networking/ParseBaseStation.cpp
src/Networking/ParseBaseStation.h
src/Networking/ParseCAN.cpp
src/Networking/TestPackets.cpp
src/Networking/TestPackets.h
src/Networking/tests.cpp
src/Rover.cpp

This is a fairly big PR that moves around a lot of files. The main changes:
(1) Create FakeBaseStation and FakeCANBoard executables. Run these and Rover in three separate processes and watch the Rover handle requests from both directions! (You'll need to set up a virtural can network using the shell commands shown in CANUtils.cpp.)
(2) Improves error handling for network calls
(3) Pulls out CAN I/O, test CAN packet construction, and Base Station message handling into separate files.

Rover main loop now handles CAN and base station communication

---

README.md

The install instructions were incorrect and used a flag that only exists in newer versions of CMake, that (strangely) older versions just silently ignore. I changed this to just use the "old" way of creating and using a CMake build directory.
Additionally, the new AR detection code that is being worked on will require use of the ARUco module for OpenCV; this module isn't built in unfortunately so it needs to be downloaded and installed before OpenCV is built. I've updated the instructions to show how to do this.

Update README.md to correct OpenCV installation instructions

---

README.md

Bruh moment... Apparently if you don't have a line break before continuing the numbered list in Markdown, it just puts all the items in a paragraph instead of making a list. I fixed it now. :man_facepalming: 
Really not sure how I messed this one up folks :/

Fix number formatting in README

---

src/CMakeLists.txt

This new version of the simulator avoids the dependency on the `X11` library and does not try to launch windows from worker threads (which apparently is not allowed on OSX). However, I think it requires updating to SFML 2.5, which may require building from source.

Update to new simulator master

---

README.md
tests-docker-action/entrypoint.sh

The default branch of the Catch2 GitHub repository is now on a version 3 preview which has a different file organization and naming scheme that causes errors when trying to find catch2/catch.hpp when building this repository (on both local machines and the Docker CI). This pull request ensures that we are using a compatible version of catch2 that includes a catch.hpp file by checking out to the latest release on the v2.x branch of the Catch2 GitHub repository. The README and docker entrypoint have been updated to include this extra step.
This could be a temporary fix if we plan to move to v3 of Catch2, as that would require some more effort.

Use Compatible Catch2 Version

---

src/Rover.cpp

Rover.cpp was not rate-limited at all, and the simulator did rate-limiting only approximately (assuming the other code took no time to execute). This fixes both. (Since the simulator code is a submodule, this was updated upstream.)
Arguably, we should treat the simulator as a black box and handle its weird rate limiting with code on the rover, since executing things on the real robot are bound to have similar issues. Still, there's no real reason not to make this cleaner.

Improve rate limiting for Rover.cpp and simulator

---

src/filters/KalmanFilter.h

I was looking over my math and I realized I had an extra set of parenthesis that changed the meaning of the equation.
It should be solving the equation S^T * K^T = A * P^T for the matrix K, but it was instead solving S^T * K = (A * P^T)^T for K, which is incorrect.

Fixed bug in KF math

---

src/Autonomous.cpp
src/Autonomous.h
src/Rover.cpp
src/SimpleAutonomousTester.cpp

Using URCLeg instead is important, because we also need to know when the
AR tag is visible to the cameras.
I tested this using the `getLeg(0)` instead of `getLeg(1)` and it works great!

Switch target from PointXY -> URCLeg

---

src/Autonomous.cpp
src/Autonomous.h
src/Rover.cpp

Once the rover gets close enough to the goal, we put it into a state
that indicates it should use the final target orientation, rather than
trying to aim the rover towards the goal.

Implement navigation state and target orientations

---

src/Autonomous.cpp

Angles are modular, so a difference of 2pi radians is the same as a difference of 0 radians.
Also, a difference of 3pi/2 radians is the same as a difference of -pi/2 radians.

Fix dist function to work for angles that are larger than 2pi radians apart

---

src/Autonomous.cpp
src/Autonomous.h
src/CMakeLists.txt
src/Rover.cpp

This also implements showing a visualization window so we can visualize
what the rover is planning to do.
The current code replans once every two seconds and in the mean time
does a hacky kind of pure pursuit.
Due to the infrequent replanning, sometimes the rover crashes before
replanning is triggered. In a future PR, we should fix this by verifying
the plan at each timestep using the most recent lidar scans.

Implement A* planning for obstacle avoidance

---

src/CMakeLists.txt
src/ar/CMakeLists.txt
src/ar/calibration.cpp

When we originally set up the AR detection code, we had a few demo/tester programs that needed to be built within the context of the rest of the project, so we added this directory as a subdirectory in CMake. At some point, the CMakeLists file changed to explicitly define all executables and source files in the top-level CMakeLists.txt, which is fine, but somewhere the `add_subdirectory(ar)` line got removed and we can't build our test program now, since the CMakeLists.txt file that exists in the `ar` subdirectory isn't a full CMake file; it's intended to be included in a full CMake file.
This pull request adds the `add_subdirectory(ar)` line back to the main CMakeLists.txt file. In order to avoid cluttering the build directory and building tester programs that might not be necessary, the …

Add AR subdirectory back to CMakeLists.txt

---

src/filters/RollingAvgFilter.h

While writing unit tests, I found this bug in the rolling average filter. The size and index fields are not initialized on startup, so they have arbitrary values at the beginning, causing the filter to break.
This is pretty easily fixed by initializing them to 0.

Fix bug in RollingAvgFilter

---

src/filters/RollingAvgFilter.h

It seems that my environment *usually* zero-initialized vectors, but this isn't guaranteed or enforced, so it would randomly and infrequently fail unit tests.
Explicitly initializing the vector used to sum the data points to zero fixed this. I've tested it many times since, so hopefully this should be ironed out.

hopefully the last fix to RollingAvgFilter

---

src/Autonomous.cpp

More of the same mistake where I didn't explicitly zero-init a vector. It seems to work most of the time since it was usually zero-initialized but that's not guaranteed.
I've grepped through the rest of the project and I'm pretty sure there are no other occurrences of this mistake.

Explicitly zero-init vector when calibrating

---

src/Autonomous.cpp
src/Autonomous.h

Adds a spiral search pattern for when the rover arrives at the provided GPS coordinates but cannot see the target landmark. The rover also replans more often so as to speed up the search. The `arrived` function has also been updated to only return true when the rover has reached the landmark post.
The spiral search pattern roughly follows the polar curve r = θ starting at θ = π. The rover moves along this curve by navigating between points on the curve with θ intervals of `search_theta_increment`. `search_theta_increment` decreases as the rover moves further away from the center, so that the spiral shape is maintained. The current A* planning is used to navigate between points.
The search currently does not try to avoid obstacles, and points can be placed inside obstacles where they …

Spiral search pattern

---

src/Autonomous.cpp
src/Autonomous.h

(1) We only switch to a new plan if its cost is significantly lower than
the current plan's cost.
(2) We stop the robot if the plan collides with an object near the
robot.
(3) As a refactor, the "should_replan" boolean is removed in favor of
just setting the plan cost to INFINITE_COST.
Screencap demo of current capabilities: https://huskyrobotics20-21.slack.com/files/U01B55M6DNV/F01MM8KTEM7/no_collisions.mp4

Improve collision avoidance for planning

---

README.md
src/Autonomous.cpp
src/Autonomous.h
src/CMakeLists.txt
src/PlanViz.cpp
src/Rover.cpp
tests-docker-action/Dockerfile
tests-docker-action/entrypoint.sh
tests-docker-action/rover-test-deps-ros-Dockerfile

This pull request fixes the issue of two SFML windows not being supported on some OSs, causing the simulator and plan visualization not being able to run. The simulator now publishes information for visualization to a ROS topic, and the new PlanViz executable reads information from the topic and displays it. The simulator and plan visualization are now different executables (RoverSim and PlanViz), so a simulator window can be run without visualization and vice versa.
I have also updated the Docker CI to include ROS2. It is now based on Ubuntu 20.04, as support for the ROS2 version that targets Ubuntu 18.04 is ending in May. I have also added a reference version of the Dockerfile used to create the CI image so it is easier to access if it needs to be updated in the future. It is based on …

ROS2 Plan Visualization

---

src/CMakeLists.txt
src/Networking/CANUtils.cpp
src/Networking/FakeCANBoard.cpp
src/Networking/ParseBaseStation.cpp
src/Networking/ParseCAN.cpp
src/Networking/real_world_interface.cpp
src/Networking/tests.cpp
src/Rover.cpp

The very conservative MAX_X_VEL and MAX_TH_VEL values in ParseBaseStation.cpp will be annoying when working with the simulator, but I think for now it's best (safest) to set these to small values.
The FakeCANBoard changes are unrelated, but still worth merging as this ended up being the most useful way to test PWM packets.
Video using the changes from this PR: https://photos.app.goo.gl/8u72LgDHG7dh9FT38

Implement setCmdVel for the actual rover

---

src/worldmap/GlobalMap.cpp

GlobalMap uses the matrix inverse but doesn't include `<Eigen/LU>`, so this is a quick fix to that.

Added missing include

---

DEFAULT_FASTRTPS_PROFILES.xml

ROS2, unlike ROS, uses some fancy middleware protocol for discovering
other nodes on the network. For some reason, it wasn't working when
connecting my laptop to the rover. So instead, we use this XML file to
explicitly tell ROS nodes which IP addresses to connect to.
Usage: This XML file needs to be in the same directory as the executable
and/or the current working directory of your shell. So on the rover, put
it in the `build` directory and make sure your shell is "in" that directory
before trying to run any commands like `./Rover`.
40.40.40.40 is a fake IP address to test whether the XML file is
actually being loaded by ROS2. You can check this with:
sudo tcpdump -v | grep 40.40.40.40
The other two IP addresses are my laptop and the rover (in the ME annex
building's network).

Add DEFAULT_FASTRTPS_PROFILES.xml

---

README.md
src/CMakeLists.txt
tests-docker-action/rover-test-deps-ros-Dockerfile

Our install instructions are currently to do a custom source build of OpenCV 3 with certain contrib modules mixed in; however, this is pretty unhygienic and wasteful to do on every new setup, and we probably ought to be using the version that comes with the system package manager. On most current Ubuntu installations OpenCV 4 is packaged; we've tested and it seems to be compatible (at least, the parts we used in our code) out of the box with OpenCV 3, so no code changes should be required to move to OpenCV 4 installed from APT. 
All this pull request really does is update the install instructions and change the Dockerfile that defines the image the CI runs tests on to also use those install instructions instead of building from source.

Update OpenCV install instructions

---

src/Networking/json.hpp

The header-only JSON library we're using has had two minor version updates since we checked it in. It's probably not a big deal and I don't think we've actually run into any problems but just for the sake of maintenance we should probably update it. There have also been numerous bug fixes since then so we never know when we could run into those. CI shows the update doesn't break anything, and the library is header-only so it's pretty self contained, meaning the update is pretty simple.

Update JSON library to version 3.9.1

---

src/ar/calibration.cpp

This pull request updates the calibration sample program to the latest version that is available in OpenCV 4. Notable changes include the use of the "releasing-object" method of camera calibration, which is more accurate for less precise calibration targets (like the printed paper targets we will most likely be using). We probably ought to use this when we calibrate the cameras on the rover. I'll update the documentation on camera calibration to include info on this.
Note that this new program uses functions that have been introduced in OpenCV 4, so as such OpenCV 4 will be *required* to build it. I don't actually think it will affect the entire project, you have to explicitly specify that you want to build the calibration program so people using OpenCV 3 should still be fine for the time …

Update calibration program to latest version, from OpenCV 4

---

src/CMakeLists.txt
src/Rover.cpp
src/Rover.h
src/TunePID.cpp

There are three CAN messages we need to send to the motor boards in order to initialize encoder sensor measurements. This PR makes it so we send those messages automatically when starting the `Rover` executable.
This PR also adds a script to help tune PID coefficients. The script sends a trajectory of target angles (currently a sine wave of amplitude 15 degrees and period 3 seconds) to the motor boards and measures the actual angles as reported by the encoders. The idea is that a human operator will run this script several times for each motor, tweaking the PID coefficients, until we get good trajectory tracking performance. I have not actually tested this script yet, because we haven't yet gotten good data from the encoders.
In the course of compiling this script, I reorganized our …

Add code to Rover.cpp to initialize encoders & add PID tuning script

---

src/Networking/FakeCANBoard.cpp
src/Rover.cpp
src/Rover.h
src/TunePID.cpp

Changes TunePID script to allow starting at a nonzero angle (which is
important to avoid possible issues with negative underflow).
Also makes it possible to set a different PPJR for each arm joint.
Also adds a simpler script (in FakeCANBoard.cpp) for testing PID
control with constant angles rather than time-varying angles.

Fix some bugs for PID control

---

src/CMakeLists.txt
src/Networking/FakeCANBoard.cpp
src/Networking/ParseBaseStation.cpp
src/Networking/ParseCAN.cpp
src/Networking/motor_interface.cpp
src/Networking/tests.cpp
src/Rover.cpp
src/log.cpp

A bunch of code changes that I found useful while doing on-rover testing today.
- Implement sending actual e-stop packets
- Easier-to-use FakeCANBoard script
- Additional logging messages in the Rover.cpp main loop
- some other small changes

More changes to PID testing code

---

src/Autonomous.cpp
src/Autonomous.h

Changed the autonomous code to compute the plan in a separate thread using `std::async`; I opted to make it the caller's responsibility to do planning in a different thread just so I didn't have to change any of the planning code itself. The `Autonomous` class now holds a `std::future` object which represents a pending plan, and every time it would recompute a plan it checks if one is already pending before dispatching a thread to compute one. Tested using the simulator and it seems to work fine, but I don't have much experience with the planning code so let me know if anything is wrong.

Do planning in separate thread

---

DEFAULT_FASTRTPS_PROFILES.xml
src/Networking/Network.cpp
src/Rover.cpp

The IP addresses of the base station and the rover are different on the antenna network. This PR adds those IP addresses to the DEFAULT_FASTRTPS_PROFILES.xml (used by ROS2 for peer discovery) and changes the rover initialization code to pull the server IP address from the environment variable `SSH_CLIENT` (which makes it so we don't need to recompile the program every time the server IP address changes).
There's also a small unrelated change: we fixed the PPJR bug on the shoulder board, so we now have a better estimate for the PPJR for that joint.

Networking improvements

---

src/Networking/NetworkingStubs.cpp
src/Networking/NetworkingStubs.h
src/Networking/ParseBaseStation.cpp
src/Networking/motor_interface.cpp
src/Networking/motor_interface.h
src/Networking/tests.cpp
src/Rover.cpp
src/Rover.h
src/TunePID.cpp

The base station can now send JSON packets of the format
{'type':'motor','motor':'arm_base','incremental PID speed':1.0}
This is similar to PWM control except that it uses feedback from the
encoders to keep the arm moving at a consistent speed (regardless of
external factors such as carrying a weight, for example).
This code handles tracking whether each mode is using PID or PWM control
and switching the motor board modes as necessary.
It also implements a little bit of the inverse kinematics version of
this: we also accept JSON packets of the format
{'type':'motor','motor':'IK_X','incremental IK speed':1.0}
except that we'll return an error saying we haven't implemented this
yet.

Implement incremental PID interface for arm motors

---

src/Constants.h
src/Networking/IK.cpp
src/Networking/IK.h
src/Networking/motor_interface.h
src/Networking/tests.cpp

This PR implements a `forward_kinematics()` method that computes the (x,y,z) position of the hand relative to the arm base, given the current arm angles as reported by the motor encoders. The constants for the lengths of the arm segments and the sign flips for the motor encoders are unknown. I'll do a follow up PR to set those constants after trying things out on the actual rover.

Forward kinematics

---

src/Autonomous.cpp
src/Autonomous.h
src/CMakeLists.txt
src/Rover.cpp
src/example_gps_legs.txt
src/gps/read_usb_gps.h

This PR implements sequencing multiple autonomous legs. When the rover completes a leg, it will start the next leg once the enter key has been pressed in the terminal. This works well in the simulator, but we may want to send this as a command from the base station when used on the real rover.
This also implements parsing autonomous legs from GPS coordinates in a well-formatted file. The filepath can be changed in `Rover.cpp`. If no file is given or the file doesn't exist or contains no valid legs, the default simulator legs are used.
There are also some small refactors included.

Implement autonomous leg sequencing

---

rover-config/.motion/motion.conf

We have to build from source in order to get this on Ubuntu 18.04, but it seems to be worth it (allows higher-resolution streaming and grayscale streaming if we want). It also fixes the bug where we could only stream two cameras at a time!

Use higher-res video streaming with Motion 4.2

---

Doxyfile
doxygen-tags/rclcpp.tag

Similarly to what I did for OpenCV, Eigen, etc. I managed to get a Doxygen tag file for the ROS client library so we can link to the documentation for symbols from the library in our own documentation, rather than just leaving them as plain text.
ROS is set up as a ton of small repositories each with its own Doxygen config and tag files, and by default the setting to generate tag files is disabled in every ROS repo, so I chose not to include rclcpp tags in the first commit I did to add Doxygen tags just for the sake of time. Here it is now.

Add Doxygen tag file for rclcpp and clean up Doxyfile a bit

---

src/ar/ARTester.cpp
src/ar/Detector.cpp
src/ar/Detector.h
src/ar/read_landmarks.cpp

Improved some parts of the AR detection system; in particular, the `Detector` class now corrects passed-in images for lens distortion which should hopefully improve the ability of the system to approximate the sides of the tags using straight lines. We also made some internal changes that allow the client to change the settings of the underlying ARUco detection code after a `Detector` is constructed. 
We modified the `ARTester` to just use a plain `VideoCapture` object from OpenCV so it could read frames from the input synchronously; the camera system works well for reading live camera feeds, but if asked to stop or used on a video file, it will consume all the available input in its background thread, which makes it bad for the `ARTester`. The change made the tester program pretty messy …

Improve AR tag detection somewhat

---

src/Autonomous.cpp
src/Autonomous.h
src/Rover.cpp

With a queue, once a target is popped from the queue, it disappears from memory. Using a std::vector seems a bit more flexible to me, in case we want to go back to previous targets or skip ahead to some future target.

Use a vector for urc_targets instead of popping from a queue

---

src/Autonomous.cpp
src/planning/plan.cpp

1. Fixes a thread safety issue with `computePlan` (we were passing the lidar points by reference, which could be an issue if the outside function returns while `computePlan` is still running).
2. Decreases epsilon for weighted A* (more expensive, but better plans)
3. Update to new `FriendlyGraph` API (and increase the std for GPS data, to try to make the pose estimates less jittery).

Three small tweaks to autonomy system

---

src/Autonomous.cpp
src/Autonomous.h

Previously we used a filter, which essentially took a moving average of
the location estimates over time. However, now that the pose graph
solves may suddenly shift the robot's estimated location, just taking
the average of the post location estimates is not a good idea.
Fortunately, the pose graph itself can solve for landmark locations if
we give it the data. This commit implements that.

Implement using pose graph optimization to estimate landmark locations

---

src/Autonomous.cpp
src/Autonomous.h
src/CMakeLists.txt
src/Rover.cpp
src/rospub.cpp
src/rospub.h

I thought that including rclcpp.h was slowing down compilation for
Rover.cpp and Autonomous.cpp, so I decided to move that into a separate
file rospub.cpp so that we don't need to recompile the publishing logic
every time we e.g. add a print statement to Autonomous.cpp for
debugging.
In the end, I'm not sure this actually improved compile times by much,
but I think it's a nice refactor regardless. Anything that shortens the
Autonomous.cpp file is a good thing, IMO....

Move ROS publishing to a separate .cpp file

---

Doxyfile
src/Networking/CANUtils.cpp

Since this repo is now named Resurgence we probably should change the name wherever it occurs internally.

Change PY2020 to Resurgence in several places

---

src/gps/read_usb_gps.cpp
src/world_interface/noop_world.cpp
src/world_interface/real_world_interface.cpp
src/world_interface/simulator_world.cpp
src/world_interface/world_interface.h

Related to [this task](https://app.clickup.com/t/1mzuhpw) on ClickUp.
No world_interface methods have been added or removed yet, this simply refactors existing methods to use the newly added `DataPoint` class, which provides utility for checking data freshness, representing an invalid measurement, etc. Additionally, documentation has been added to the methods in `world_interface.h`.
To check if data is new, we just have to save the old timestamp and compare against the current one. Additionally, we can also see how old the data is by checking `dataclock::now() - dataPoint.time`.
Additionally, I added a header guard, as well as standardizing time measurement utilities. Now, to measure time, we can just use `dataclock::now()`, which returns a `datatime_t`.

changed world_interface.h to use new DataPoint class, added header guard

---

.clang-format

Edit the clang format file to allow short functions to be on a single line

Clang-Format: Allow short functions to be on one line

---

.clang-format

I didn't realize in my last clang-format PR that setting `AllowShortFunctionsOnASingleLine: true` would make _all_ short functions be on a single line, which isn't ideal.
Setting it to `Empty` instead only makes empty functions be on a single line, which I think is better.
Sorry about the duplicate PR, I'm not super familiar with clang format.

Change clang format to only allow empty functions on single line

---

src/Networking/motor_interface.cpp
src/world_interface/noop_world.cpp
src/world_interface/real_world_interface.cpp
src/world_interface/simulator_world.cpp
src/world_interface/world_interface.h

Moved motor control methods from `motor_interface` to `world_interface`, since I think that makes more sense. Additionally, that allows code other than the networking code to control those motors.
Additionally, I added a `getCmdVel()` method, as well as a `readVisualOdomVel()` in anticipation of visual odometry.
Let me know if there are other things that should be added to `world_interface`, or if there's something else that I missed.

Add methods to world_interface

---

src/world_interface/real_world_interface.cpp

Very minor fix, I just noticed that initializing AR before setting up the cameras would cause the setup to fail.
This fixes that by setting up the cameras first.

Set up cameras before initializing AR

---

src/camera/Camera.h
src/camera/CameraConfig.h

This is a pretty minor PR.
I forgot to move over a doxy comment along with the camera config file constants before, so I fixed that now. Additionally, I added everything in `CameraConfig.h` to the `camera` group.

Fixed doxy comments for CameraConfig

---

src/world_interface/simulator_interface.cpp

The PWM is normalized, so it should be compared to 1, not to tangential speed, which is wrong anyway.

Minor bug fix to simulator setCmdVel()

---

src/Autonomous.cpp
src/Autonomous.h
src/Rover.cpp
src/gps/gps_util.h
src/gps/usb_gps/read_usb_gps.cpp
src/navtypes.h
src/world_interface/world_interface.h

Before, the rover would block during initialization while waiting for a fix. This is fine during the competition, but makes testing unwieldy.
Instead, the GPS coordinates of the map legs are lazily mapped to world space once the gps fix becomes available. Since the pose graph initialization required this too, the pose graph is lazily initialized too.
The robot will be automatically initialized by `autonomyIter()` when the gps fix becomes available.

Don't block rover while waiting for gps fix

---

src/Rover.cpp
src/network/websocket/WebSocketProtocol.h
src/network/websocket/WebSocketServer.cpp
src/network/websocket/WebSocketServer.h
src/world_interface/simulator_interface.cpp

Changed WebSocketProtocol to be OOP friendly, use unique_ptr in WebSocketServer to avoid assignment.
See [this comment](https://github.com/huskyroboticsteam/Resurgence/pull/163#issuecomment-1205682474) for an explanation of the bug that is fixed in this PR.

Bugfixes for websockets

---

src/Constants.h
src/Rover.cpp
src/Util.cpp
src/Util.h
src/network/MissionControlProtocol.cpp
src/network/MissionControlProtocol.h
src/world_interface/data.h
src/world_interface/kinematic_common_interface.cpp

This PR adds a method that immediately calls `robot::setJointPower` but also stores requested joint power values in a map which are periodically read by a thread and sent to `robot::setJointPower` again, to prevent the motor boards' watchdog timers from killing the motors when the requested power does not change. The period is 1/3 of a second right now, but we can change that.
This is a draft PR for now until I can test the code (not sure if there is a watchdog timer on the simulator, so I will probably just put a debug print in setJointPower to make sure it's being called periodically), but I wanted to get the review process started.

Add a thread to repeat setJointPower to keep motors alive

---

src/network/MissionControlProtocol.cpp

This PR fixes a bug where the steering would reverse direction if the steer value became too large. Looking at the code, it seems that there was a misplaced negative sign, probably a typo.

Fix steering inversion bug

---

src/CMakeLists.txt

We occasionally make updates to the CAN library, so to ensure that we don't have bugs due to version mismatches, we will require a specific version.

Require specific version of HindsightCAN

---

Doxyfile

Minor change to the doxyfile to not require explicit `@brief` tags.

Enabled javadoc autobrief

---

src/CAN/CANMotor_PSOC.cpp

Priority queues are by default max queues, but we want min queues.

Fix priority queue in CAN telemetry thread

---

src/CAN/CANMotor.h
src/CAN/CANMotor_PSOC.cpp
src/CAN/FakeCANBoard.cpp

This adds the implementation of the pot init packet, as well as support for testing it through FakeCANBoard. This implementation has been tested on the rover hardware.

Added potentiometer support to CAN

---

.github/workflows/ccpp.yml
README.md

Our build breaks whenever one of our team dependencies has a newer version available that we don't want to migrate to yet. Explicitly specifying the version will fix this.

Set dep versions

---

src/CAN/CANMotor.cpp
src/CAN/CANMotor.h
src/CAN/FakeCANBoard.cpp
src/world_interface/real_world_constants.h
src/world_interface/real_world_interface.cpp

This adds code in the CAN layer to allow configuring the limit switch limits, so that the motor boards can reset encoder positions when they are triggered.

Add code to set limit switch limits

---

src/world_interface/real_world_constants.h

Agreed on Saturday that left trigger should open the hand and right trigger should close.

negate hand pwm scales

---

src/CAN/FakeCANBoard.cpp

Prompt will now continue to prompt as long as it reads invalid input. Invalid input is defined as input that cannot be converted to an integer. It still accepts any base integer (hex, octal, decimal, etc.)

Update prompt to handle invalid input and use modern language features

---

src/network/MissionControlProtocol.cpp

1) This reduced CAN bus usage
2) This is required for the limit switch calibration script, since it'll be sending power commands to the rover while the rover executable is running. Repeatedly sending zero power would cause conflicts.

Don't send zero power in power repeat task

---

src/network/MissionControlProtocol.cpp

sendRoverPos appears to crash the telemReportTask thread.

Commented out sendRoverPos in MCP

---

src/Rover.cpp

When the rover exits it should emergency stop all motors. Technically PWM will be killed by the motor watchdogs, but PID control won't be. So if the rover exits while PID is running, it'll keep executing that pid command. Which is bad.

E-Stop when exiting

---

src/network/MissionControlProtocol.cpp
src/world_interface/real_world_constants.h

Tunes the active suspension pwm scales, and also fixes the joint validator to not use a hardcoded list of joint names.

Tune active suspension, fix validator

---

src/CAN/CAN.cpp
src/CAN/CANUtils.h
src/CAN/FakeCANBoard.cpp
src/CMakeLists.txt
update_deps.sh

This lets us prompt for arbitrary telemetry types, which will be useful for pot testing, and other stuff too.

Add general telemetry prompting to FakeCANBoard

---

.clang-format
src/ardupilot/ArduPilotInterface.cpp
src/ardupilot/ArduPilotProtocol.cpp
src/network/MissionControlProtocol.cpp
src/utils/core.cpp
src/utils/core.h
src/world_interface/data.h
src/world_interface/gps_common_interface.cpp
src/world_interface/noop_world.cpp
src/world_interface/simulator_interface.cpp
src/world_interface/world_interface.h

This PR adds `readIMU()` to the world interface, which allows reading the full attitude. It also includes some refactoring, since `readIMUHeading()` is now obviously a subset of `readIMU()`.
Also includes a bugfix where `lat` was repeated twice instead of `lat` and `lon`.

Report full attitude, fix lat/lon bug, report attitude even if no gps fix

---

src/CAN/CAN.cpp
src/CAN/CANMotor.cpp
src/CAN/CANMotor_AVR.cpp
src/CAN/CANUtils.cpp
src/CAN/FakeCANBoard.cpp
src/CAN/TestIMU.cpp
src/CMakeLists.txt
update_deps.sh

This PR makes it so that HindsightCAN no longer needs to be installed with `apt-get`, and uses `FetchContent` to fetch it at configure-time instead. This makes it easier to develop in the future, and removes the hassle of managing that dependency in the ubuntu repo.
This should be merged after the corresponding PR in HindsightCAN: https://github.com/huskyroboticsteam/HindsightCAN/pull/47
Note: remember to update the commit hash in CMakeLists.txt after merging the above pr.

Install hindsightcan with fetchcontent

---

src/Rover.cpp
src/Util.h
src/commands/DriveToWaypointCommand.h
src/control/JacobianVelController.h
src/control/PIDControl.h
src/control/PlanarArmController.h
src/control/TrapezoidalVelocityProfile.h
src/filters/FullPoseEstimator.cpp
src/filters/PoseEstimator.cpp
src/filters/PoseEstimatorLinear.cpp
src/filters/pose_graph/friendly_graph.cpp
src/kinematics/DiffDriveKinematics.cpp
src/kinematics/SwerveDriveKinematics.cpp
src/planning/plan.cpp
src/world_interface/data.h
src/world_interface/kinematic_common_interface.cpp
src/world_interface/real_world_interface.cpp
src/world_interface/simulator_interface.cpp
tests/util/UtilTest.cpp
tests/worldmap/GlobalMapTest.cpp
tests/worldmap/TrICPTest.cpp

This removes all import references to Util.h and replaces them with the correct util file. Also, delete Util.h entirely.

Delete and remove all references to Util.h 

---

src/network/websocket/WebSocketServer.cpp

Print the current connection that's causing duplicate connections to be rejected. Helps with debugging.

Improve logging when rejecting duplicate connections

---

src/ardupilot/ArduPilotInterface.cpp
src/ardupilot/ArduPilotProtocol.cpp
src/ardupilot/ArduPilotProtocol.h
src/network/MissionControlProtocol.cpp
src/utils/transform.cpp
src/utils/transform.h
src/world_interface/gps_common_interface.cpp
src/world_interface/noop_world.cpp
src/world_interface/simulator_interface.cpp
src/world_interface/world_interface.h

Euler angles suck:
- they are ambiguous (granted, quaternions are a double-cover of SE3, but at least it's very easy to disambiguate, unlike euler angles)
- Euler angles are defined by 3 angles AND axis conventions, which will differ from code we may see in other places, and create hard-to-discover bugs, plus its hard to enforce. Quats don't have any additional associated conventions.
- Quaternions lend themselves more to linear algebra computations
The above reasons meant `readIMUHeading()` was wrong, since it wasn't giving the correct heading value, since the quat was being decomposed "incorrectly" into the euler angles. It was correct (technically), but wasn't what we wanted.
So this pr just represents rover orientation with quats instead of euler angles. And the heading is very easy …

Represent rover orientation as quaternion instead of euler angles

---

src/network/MissionControlProtocol.cpp

Minor improvement that only resends drivebase commands if they're nonzero. Note that this doesn't affect the first time it's sent, just the periodic resends.

Don't repeatedly send packets commanding 0 power to drivebase

---

.github/workflows/format-checker.yml

We were previously using 11, which has a [bug](https://reviews.llvm.org/D106349) that was messing with our enums. Upgrading to 18 should fix this.

Upgrade format checker CI to clang-format-18

---

src/kinematics/DiffDriveKinematics.cpp
src/kinematics/DiffDriveKinematics.h
src/world_interface/kinematic_common_interface.cpp
tests/kinematics/DiffDriveKinematicsTest.cpp

Sometimes we want to scale the wheel velocity so that we focus more on rotational velocity or linear velocity. There are cases where the given theta velocity and linear velocity result in a wheel speed too great for the rover.

DiffDriveKinematics: Scale wheel velocity to stay below max speed

---

src/network/MissionControlProtocol.cpp
src/network/MissionControlProtocol.h
src/network/websocket/WebSocketServer.h

Changes setArmIKEnabled packet to requestArmIKEnabled.
Adds reportArmIKEnabled packet
No longer crashes if enabling arm IK doesn't succeed. Instead it sends a new packet, reportArmIKEnabled which will let MC know if arm IK is enabled or not.

Arm Inverse Kinematics Updates

---

src/CAN/FakeCANBoard.cpp
src/CMakeLists.txt
src/ar/ARTester.cpp
src/camera/CameraParams.cpp
src/camera/CameraParams.h
src/network/MissionControlProtocol.cpp

Right now, I've made this likely as verbose as we would possibly have it. It throws warnings for 
`-Wall
-Wextra
-Wconversion
-Wpedantic`
See [here](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html).
Compile this and let me know which warnings make sense and which to suppress. Then, do we want to `-Werror` to really enforce these? This would require a lot of code cleanup to make our code compile without errors.

Improve compiler warning flags

---

.github/workflows/format-checker.yml

For some reason, git clang-format-18 --style=file --diff would exit with error code 1. This version doesn't, but also fixes the enum bracket issue that caused us to upgrade to 18.

Downgrade format checker to clang-format-14

---

src/CMakeLists.txt
src/utils/core.cpp
src/utils/core.h
src/utils/scheduler.h
tests/util/CoreTest.cpp
tests/util/SchedulerTest.cpp
tests/util/TimeTest.cpp

I'm in the process of cleaning up MissionControlProtocol, and factoring out the tasks from the big class into their own individual classes that encapsulate their own state.
This PR adds the required task classes and unit tests, in preparation of that.
I'm reasonably sure I caught any data races in `AsyncTask`, but let me know if you find any others!

Add tasks to utils

---

src/control/PlanarArmController.h

Before, the velocity wouldn't get set to zero so the arm wouldn't move but the setpoint would keep moving at the current velocity. This PR ensure it gets handled properly, so the velocity is reset and the setpoint is made to be correct.

Handle IK failure gracefully

---

src/CMakeLists.txt
src/Constants.cpp
src/Constants.h
src/network/MissionControlTasks.cpp

Moving definitions to a .cpp file makes tuning a lot faster, since only that file needs to be recompiled, otherwise editing the header files triggers a LOT of recompilation.
Besides that refactor, this PR adds a map allowing us to specify specific compression constants for streams, since we want the hand camera to be higher quality than the others.

Move constants definitions to impl file, add per-stream compression constants

---

src/CMakeLists.txt
src/Constants.cpp
src/Constants.h
src/ardupilot/ArduPilotProtocol.cpp
src/autonomous/AutonomousTask.cpp
src/autonomous/AutonomousTask.h
src/commands/DriveToWaypointCommand.cpp
src/commands/DriveToWaypointCommand.h
src/network/CMakeLists.txt
src/network/MissionControlMessages.h
src/network/MissionControlProtocol.cpp
src/network/MissionControlProtocol.h
src/utils/transform.cpp
src/world_interface/gps_common_interface.cpp
src/world_interface/real_world_constants.h
tests/commands/DriveToWaypointCommandTest.cpp

See [old PR](https://github.com/huskyroboticsteam/Resurgence/pull/223) for more detailed info/commits/reviews.

Autonomous Task

---

src/CMakeLists.txt
src/Globals.cpp
src/Globals.h
src/LimitCalib.cpp
src/Rover.cpp
src/TunePID.cpp
src/ardupilot/ArduPilotProtocol.cpp
src/autonomous/AutonomousTask.cpp
src/control_interface.cpp
src/control_interface.h
src/network/MissionControlProtocol.cpp
src/network/MissionControlTasks.cpp
src/world_interface/kinematic_common_interface.cpp
src/world_interface/noop_world.cpp
src/world_interface/real_world_interface.cpp
src/world_interface/simulator_interface.cpp
src/world_interface/world_interface.h

Our CMake is becoming a bit of a mess, and circular dependencies were cropping up. This PR doesn't fully fix this problem, but is a partial solution. This PR focuses on the use of shared global state, particularly `Globals.h`, which had become way too pervasive in our codebase.
- Moved E-Stop from globals to instead be owned by the world interface (which also makes more sense, since we should refuse to move motors if e-stopped) NOTE: there actually isn't code that checks for this, so that should be done in a follow-up PR
- Moved `kinematic_common_interface` out of the world interface layer. It has been renamed to `control_interface`, and is not part of the world interface, it is only an abstraction around it.
- Some refactoring to remove dependencies on global state, including creating a …

Fix CMake circular dependencies

---

camera-config/WristCameraCalibration.yml
src/Constants.cpp
src/world_interface/simulator_interface.cpp

Related to: https://github.com/huskyroboticsteam/mission-control/pull/69 and https://github.com/huskyroboticsteam/Simulator/pull/18
Changed the names of the cameras:
- `upperArm` -> `mast`
- `rear` -> `wrist`
- `front` -> `hand`

Changed the names of the cameras

---

enable_CAN.sh
enable_CAN_and_GPS.sh
rover-config/50-rover-cameras.rules
src/CAN/CAN.cpp
src/world_interface/real_world_interface.cpp

Reconfigure CAN to have the right datarate, update the CAN code to use can FD frames, update the camera udev rules to match the real camera device instead of the virtual metadata device (due to new video4linux kernel)

Update configurations for new jetson orin nx

---

src/CMakeLists.txt
tests/util/CoreTest.cpp
tests/util/JsonTest.cpp
tests/util/RandomTest.cpp
tests/util/ThreadingTest.cpp

running into an error when attempting to 'make tests'

Better test coverage
